apiVersion: v1
kind: Service
metadata:
  labels:
    app: currency-exchange
  name: currency-exchange
  namespace: exchange
spec:
  selector:
    app: currency-exchange
  ports:
    - name: http
      port: 8181
      targetPort: 8181
  type: ClusterIP
