server:
  port: ${SERVER_PORT:8181}

spring:
  application:
    name: currency-exchange
  
  datasource:
    # Local development uses H2, cloud can use external databases
    url: ${DATABASE_URL:jdbc:h2:mem:testdb}
    driver-class-name: ${DATABASE_DRIVER:org.h2.Driver}
    username: ${DATABASE_USERNAME:sa}
    password: ${DATABASE_PASSWORD:}
  
  h2:
    console:
      enabled: ${H2_CONSOLE_ENABLED:true}  # Disable in production
      path: /h2-console
  
  jpa:
    database-platform: ${JPA_DATABASE_PLATFORM:org.hibernate.dialect.H2Dialect}
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO:create-drop}  # Use 'validate' in production
    show-sql: ${JPA_SHOW_SQL:true}          # Set to false in production
    defer-datasource-initialization: true
  
  sql:
    init:
      mode: ${SQL_INIT_MODE:always}

# Micrometer Tracing Configuration
management:
  tracing:
    enabled: true
    sampling:
      probability: 1.0
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,env
  endpoint.health.probes.enabled: true
# Actuator configuration moved to common-util module

# Logging Configuration
logging:
  level:
    com.amsidh.mvc: ${LOG_LEVEL_APP:INFO}
    org.springframework.web: ${LOG_LEVEL_WEB:INFO}

# Common utilities configuration removed - no longer needed

# OpenAPI Info (service-specific)
springdoc:
  info:
    title: Currency Exchange API
    description: Exchange rates service API
    version: ${APPLICATION_VERSION:0.0.1}