apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: currency-conversion
  name: currency-conversion
  namespace: conversion
spec:
  replicas: 1
  selector:
    matchLabels:
      app: currency-conversion
  template:
    metadata:
      labels:
        app: currency-conversion
    spec:
      containers:
        - name: currency-conversion
          image: amsidhmicroservice/currency-conversion:latest
          imagePullPolicy: Always
          env:
            #- name: CURRENCY_EXCHANGE_SERVICE_URL
            #  value: "http://currency-exchange.currency.svc.cluster.local:8181"
            - name: CURRENCY_EXCHANGE_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: currency-conversion-cm
                  key: CURRENCY_EXCHANGE_SERVICE_URL
          ports:
            - containerPort: 8282
              protocol: TCP
          startupProbe:
            tcpSocket:
              port: 8282
            initialDelaySeconds: 90
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 90
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8282
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
            successThreshold: 1
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8282
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
            successThreshold: 1
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "250m"
      restartPolicy: Always
  strategy:
    type: Recreate
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
---

