apiVersion: v1
kind: Service
metadata:
  labels:
    app: currency-conversion
  name: currency-conversion
  namespace: conversion
spec:
  selector:
    app: currency-conversion
  ports:
    - name: http
      port: 8282
      targetPort: 8282
  type: LoadBalancer
---

