server:
  port: ${SERVER_PORT:8282}

spring:
  application:
    name: currency-conversion

  # Spring Cloud Configuration
  cloud:
    compatibility-verifier:
      enabled: false
    # Configure OpenFeign per-client settings (preferred property path in recent Spring Cloud)
    openfeign:
      client:
        config:
          currency-exchange:  # Must match @FeignClient(name = "currency-exchange")
            url: ${CURRENCY_EXCHANGE_SERVICE_URL:http://localhost:8181}
          default:
            connectTimeout: ${FEIGN_CONNECT_TIMEOUT:10000}
            readTimeout: ${FEIGN_READ_TIMEOUT:10000}

# Micrometer Tracing Configuration
management:
  tracing:
    enabled: true
    sampling:
      probability: 1.0
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,env
  endpoint.health.probes.enabled: true
  
# Currency Exchange Service Configuration
currency-exchange:
  service:
    # This can be overridden by environment variables or external config
    # Examples:
    # Local: http://localhost:8181
    # AWS ECS: http://currency-exchange-service:8181
    # Kubernetes: http://currency-exchange-service.default.svc.cluster.local:8181
    # AWS ALB: https://currency-exchange.yourdomain.com
    url: ${CURRENCY_EXCHANGE_SERVICE_URL:http://localhost:8181}

# Legacy Feign property path retained for backward compatibility (optional)
# feign:
#   client:
#     config:
#       currency-exchange:
#         url: ${CURRENCY_EXCHANGE_SERVICE_URL:http://localhost:8181}
#       default:
#         connect-timeout: ${FEIGN_CONNECT_TIMEOUT:10000}
#         read-timeout: ${FEIGN_READ_TIMEOUT:10000}

# Logging Configuration
logging:
  level:
    io.github.resilience4j: DEBUG
    com.amsidh.mvc: DEBUG
    org.springframework.aop: DEBUG
    com.amsidh.mvc.client: ${LOG_LEVEL_CLIENT:INFO}  # Changed to INFO for production
    org.springframework.cloud.openfeign: ${LOG_LEVEL_FEIGN:INFO}
    org.springframework.web: ${LOG_LEVEL_WEB:INFO}

# Actuator configuration moved to common-util module

# Enable Resilience4j Management and Monitoring
resilience4j:
  circuitbreaker:
    configs:
      default:
        registerHealthIndicator: true
        metrics:
          enabled: true
  retry:
    configs:
      default:
        registerHealthIndicator: true
        metrics:
          enabled: true
  ratelimiter:
    configs:
      default:
        registerHealthIndicator: true
        metrics:
          enabled: true
  bulkhead:
    configs:
      default:
        registerHealthIndicator: true
        metrics:
          enabled: true
  timelimiter:
    configs:
      default:
        registerHealthIndicator: true
        metrics:
          enabled: true

# Common utilities configuration removed - no longer needed

# OpenAPI Info (service-specific)
springdoc:
  info:
    title: Currency Conversion API
    description: Currency conversion service API
    version: ${APPLICATION_VERSION:0.0.1}