site_name: Currency Service
site_description: Documentation for Currency Exchange and Currency Conversion microservices
use_directory_urls: true

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.highlight
    - content.code.copy
  palette:
    - scheme: default
      primary: indigo
      accent: teal
    - scheme: slate
      primary: indigo
      accent: teal

plugins:
  - search
  - mermaid2:
      arguments:
        startOnLoad: true
        securityLevel: "loose"
        theme: neutral
      javascript: https://cdn.jsdelivr.net/npm/mermaid@10.9.1/dist/mermaid.min.js

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      use_pygments: false
  - pymdownx.inlinehilite
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - md_in_html

extra_css:
  - https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css
  - stylesheets/extra.css?v=2

extra_javascript:
  - https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js
  - javascripts/inline-copy.js?v=2

nav:
  - Home: index.md
  - Architecture:
      - Overview: architecture/overview.md
      - High Level Design (HLD): architecture/hld.md
      - Low Level Design (LLD): architecture/lld.md
      - Sequence Diagrams: architecture/sequence.md
      - Class Diagrams: architecture/class.md
  - Services:
      - Currency Exchange: services/exchange.md
      - Currency Conversion: services/conversion.md
  - Database:
      - Design: database/design.md
      - H2 Scripts: database/h2.md
      - MySQL Scripts: database/mysql.md
  - Development Documentation:
      - Developer Guide: development.md
      - Postman Collection: postman/collection.json
  - Deployment:
      - Guide: deployment.md
  - API Reference:
      - Exchange API: api/exchange.md
      - Conversion API: api/conversion.md
